table_rail_joint:
  acceleration: 1.0
  deceleration: 2.0
shoulder_pan_joint:
  acceleration: 1.0
  deceleration: 2.0
shoulder_lift_joint:
  acceleration: 1.0
  deceleration: 2.0
elbow_joint:
  acceleration: 1.0
  deceleration: 2.0
wrist_1_joint:
  acceleration: 1.0
  deceleration: 2.0
wrist_2_joint:
  acceleration: 1.0
  deceleration: 2.0
wrist_3_joint:
  acceleration: 1.0
  deceleration: 2.0
